### ISSUE TITLE
Create UI based on readme data

### ISSUE THREAD

**Issue by greybax** [greybax/IT-films#2]
Just for example https://weichiachang.github.io/awesome-singer-official-portal/

**Comment by ReneVolution** [comment]
This sounds interesting. May I take it?

**Comment by greybax** [comment]
@ReneVolution Yes, sure! pls do 👍

**Comment by ReneVolution** [comment]
Hey there, I have created a simple setup with PR #7. What do you think?

**Comment by greybax** [comment]
Now we have data just in markdown format. I suppose that make sense to use json format for storing film data. In this case it can be more usable for this task.

**Comment by ReneVolution** [comment]
Sorry, I can't really follow ... where comes the json format from? Are you planning to change the format?

**Comment by greybax** [comment]
I've just think that json format could help to us with this task. But I didn't know about docsify. Seems that PR #7 looks pretty good! Let's go forward with it.

**Comment by ReneVolution** [comment]
Oh, yes. Either json or yaml might be worth looking at. We could go for a jekyll version of this. Like, a bit more shiny 😸. But for a starter, this might be good enough.

**Comment by greybax** [comment]
https://github.com/greybax/IT-films/pull/7

**Comment by greybax** [comment]
Live Website: https://greybax.github.com/IT-films
