### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by greybax** [greybax/IT-films#36]
Would be nice to have a cool logo for our project. Will appreciate any ideas and designs! 🎨 

**Please add a link in your PR to this issue.**

**Comment by agscdv** [comment]
¿Sobre que quisieras que tratara el logo?

**Comment by greybax** [comment]
@akashd50 yes, sure. It would be great to have some examples with some popular resolutions (small/meduim/large).

**Comment by greybax** [comment]
`.svg` format would be awesome to have! 😄

**Comment by ravikantvicky** [comment]
Added logo assets/it-films.svg #44 
Please review.

**Comment by VanishedApps** [comment]
Added a logo assets/logo_itfilms.png #45

**Comment by greybax** [comment]
some ideas too #40 #41

**Comment by greybax** [comment]
PR #48 is looking really good for me! Let's go forward with it! 👍

**Comment by greybax** [comment]
Thank you for all your propositions! 
Approved logo by @PaulaAsto
